spring:
  application:
    name: clean
  #MySql
  datasource:
    url: jdbc:mysql://localhost:3306/lecture_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root123!@#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

